CREATE TABLE affiliate_payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  affiliate_id INT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  payment_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  note VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (affiliate_id) REFERENCES users(id) ON DELETE CASCADE
);
