CREATE TABLE commission_settings (
  id INT PRIMARY KEY AUTO_INCREMENT,
  commission_amount DECIMAL(10,2) NOT NULL DEFAULT 50,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
